# sensitive database information
apiVersion: v1
kind: Secret
metadata:
  name: db-secret 
data:
  username: <base64-me>  	# base64 encoded 'Secret' username
  password: <base64-me> 	# base64 encoded 'Secret' password

